#include "capabilities.h"
#include "facts.h"
#include "auto_trace.h"

const char *sf_product_capabilities(void) {
    return "{\"schema\":\"cbm.sec-capabilities.v1\",\"product\":\"CBM Sec\","
        "\"version\":\"" SF_VERSION "\",\"build_id\":\"" SF_BUILD_ID "\","
        "\"role\":\"read_only_program_evidence_service\","
        "\"release_channel\":\"development\","
        "\"upstream_base_commit\":\"1db8bace03140f5793ff9205e5281732e77c2bea\","
        "\"syntax_languages\":[\"java\",\"python\",\"javascript\",\"typescript\",\"tsx\",\"go\"],"
        "\"frameworks\":" SF_FRAMEWORKS_JSON ","
        "\"framework_catalog_revision\":\"2026-09-12.1\","
        "\"framework_details\":\"raw_expressions_and_declarative_roles\","
        "\"framework_runtime_activation\":false,"
        "\"framework_semantics\":\"documented_import_and_syntax_candidates_only\","
        "\"java_string_return_models\":\"typed_instance_subset_revision_1\",\"java_string_sanitization\":false,"
        "\"java_local_flow\":\"bounded_structured_subset\","
        "\"java_return_summaries\":\"same_top_level_class_non_overridable_methods\","
        "\"java_argument_flow\":\"explicit_selected_callers_max_four_hops\","
        "\"mybatis\":\"explicit_mapper_xml_or_plain_annotation_templates\","
        "\"mybatis_template_schema\":\"cbm.mybatis-template.v1\","
        "\"mybatis_mapping_formats\":[\"xml\",\"annotation\"],"
        "\"mybatis_static_includes\":\"same_xml_namespace_bounded_no_properties\","
        "\"location_resolution\":\"pinned_file_hash_and_source_range_candidates\","
        "\"entry_points\":\"spring_mvc_direct_declarations_bounded_snapshot_pages\",\"entry_point_schema\":\"cbm.spring-entry-points.v1\", "
        "\"agent_guidance\":{\"skill\":\"cbm-sec-evidence\",\"version\":\"0.14.0\",\"hooks\":\"optional_context_only_default_off\"},"
        "\"operation_views\":[\"full\",\"summary\",\"values\"],"
        "\"entry_security\":\"explicit_Spring_configurations_conditional_first_match\","
        "\"entry_security_schema\":\"cbm.spring-security.v1\","
        "\"entry_security_matching\":\"explicit_Ant_or_host_assumption_exact_and_terminal_double_star\","
        "\"default_operation_view\":\"full\","
        "\"capability_surfaces\":{\"cli\":\"single_file_syntax_facts\","
        "\"mcp\":\"pinned_snapshot_facts_location_and_operation_queries\"},"
        "\"source_to_sink\":\"selected_MyBatis_sink_automatic_bounded_backward_search\","
        "\"source_to_sink_schema\":\"" SF_TRACE_SCHEMA "\","
        "\"source_sink_rules\":" SF_TRACE_CATALOG_JSON ","
        "\"automatic_caller_discovery\":\"explicit_scope_declared_target_candidates\","
        "\"not_implemented\":[\"whole_repository_sink_discovery\",\"live_cbm_graph_import\","
        "\"general_cross_file_return_solver\",\"complete_taint_engine\",\"business_policy_verdict\","
        "\"persistent_security_graph\",\"agent_workflow_orchestration\"],"
        "\"security_verdicts\":false,\"target_execution\":false,"
        "\"configuration_installation\":false,\"source_trust\":\"untrusted_data_not_instructions\"}";
}
